export default {
  appIcon: require('../Assets/Images/appIcon/appIcon.png'),
  loadingOut: require('../Assets/Images/loadingOut.png'),
  loadingIn: require('../Assets/Images/loadingIn.png'),
  persil: require('../Assets/Images/persil.png'),
  mdPersil: require('../Assets/Images/mdpersil.png'),
  logo: require('../Assets/Images/logo.png'),
  location: require('../Assets/Images/location.png'),
  persilmd: require('../Assets/Images/percilmd.png'),
  marketPicture: require('../Assets/Images/market.png'),
  heart: require('../Assets/Images/heart.png'),
  heartIconFill: require('../Assets/Images/heartIconFill.png'),
  omoPicture: require('../Assets/Images/omo.png'),
  alertIcon: require('../Assets/Images/alertIcon.png'),
  leftIcon: require('../Assets/Images/leftIcon.png'),
};
