//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const POST_PRODUCTS = 'POST_PRODUCTS';
export const POST_PRODUCTS_REQUEST = 'POST_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';
export const ADD_PRODUCT_IN_SHOPPING_CART = 'ADD_PRODUCT_IN_SHOPPING_CART';
export const REMOVE_PRODUCT_FROM_SHOPPING_CART =
  'REMOVE_PRODUCT_FROM_SHOPPING_CART';
//SCANS
export const GET_SCANS = 'GET_SCANS';
export const GET_SCANS_REQUEST = 'GET_SCANS_REQUEST';
export const POST_SCANS = 'POST_SCANS';
export const POST_SCANS_REQUEST = 'POST_SCANS_REQUEST';
export const SEARCH_SCANS = 'SEARCH_SCANS';
export const SEARCH_SCANS_REQUEST = 'SEARCH_SCANS_REQUEST';
export const SET_NEW_SCAN = 'SET_NEW_SCAN';
export const SET_SCANNED_BARCODE = 'SET_SCANNED_BARCODE';

//
export const CART_CALCULATE_REQUEST = 'CART_CALCULATE_REQUEST';
export const CART_CALCULATE = 'CART_CALCULATE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const GET_NEAR_PLACES = 'GET_NEAR_PLACES';
export const GET_NEAR_PLACES_REQUEST = 'GET_NEAR_PLACES_REQUEST';

export const SET_NEW_PRODUCT = 'SET_NEW_PRODUCT';

export const SHOW_COMMON_ALERT = 'SHOW_COMMON_ALERT';
export const HIDE_COMMON_ALERT = 'HIDE_COMMON_ALERT';
