//AUTH
export const GET_SKU_SUCCESS = 'GET_SKU_SUCCESS';
export const GET_SKU_REQUEST = 'GET_SKU_REQUEST';

export const EMAIL_CHECK_REQUEST = 'EMAIL_CHECK_REQUEST';
export const EMAIL_CHECK_SUCCESS = 'EMAIL_CHECK_SUCCESS';
export const EMAIL_CHECK_FAILURE = 'EMAIL_CHECK_FAILURE';
export const EMAIL_CHECK_RESET = 'EMAIL_CHECK_RESET';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_RESET = 'REGISTER_RESET';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_RESET = 'LOGIN_RESET';

export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const APPLE_LOGIN_WITHOUT_EMAIL_REQUEST =
  'APPLE_LOGIN_WITHOUT_EMAIL_REQUEST';

export const AUTO_LOGIN_REQUEST = 'AUTO_LOGIN_REQUEST';
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS';
export const AUTO_LOGIN_FAILURE = 'AUTO_LOGIN_FAILURE';
export const AUTO_LOGIN_RESET = 'AUTO_LOGIN_RESET';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

//GLOBAL

export const VERSION_CHECK_REQUEST = 'VERSION_CHECK_REQUEST';
export const SET_NEW_VERSION_DOWNLOAD_LINK = 'SET_NEW_VERSION_DOWNLOAD_LINK';
export const TOGGLE_VERSION_UPDATE_MODAL = 'TOGGLE_VERSION_UPDATE_MODAL';

export const NAVIGATE_TO = 'NAVIGATE_TO';
export const NAVIGATE_WITH_PARAMS = 'NAVIGATE_WITH_PARAMS';
export const NEW_STACK = 'NEW_STACK';
export const SWITCH_TAB = 'SWITCH_TAB';
export const POP_SCREEN = 'POP_SCREEN';
export const POP_TO_ROOT = 'POP_TO_ROOT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const RESET_APP = 'RESET_APP';
export const START_APP = 'START_APP';

export const SET_SCREEN_MAP = 'SET_SCREEN_MAP';
export const SHOW_SPINNER_OVERLAY = 'SHOW_SPINNER_OVERLAY';
export const HIDE_SPINNER_OVERLAY = 'HIDE_SPINNER_OVERLAY';
export const SET_TABBED_APP_STARTED = 'SET_TABBED_APP_STARTED';
export const CHANGE_THEME = 'CHANGE_THEME';

export const SHOW_COMMON_ALERT = 'SHOW_COMMON_ALERT';
export const HIDE_COMMON_ALERT = 'HIDE_COMMON_ALERT';

// BYK
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET';

export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const GET_SEARCH_HISTORY_STORAGE = 'GET_SEARCH_HISTORY_STORAGE';
export const ADD_SEARCH_HISTORY_STORAGE = 'ADD_SEARCH_HISTORY_STORAGE';
export const GET_SEARCH_HISTORY_API = 'GET_SEARCH_HISTORY_API';
export const SET_SEARCH_HISTORY_REDUX = 'SET_SEARCH_HISTORY_REDUX';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';

export const GET_READING_CONFIG_REQUEST = 'GET_READING_CONFIG_REQUEST';
export const SET_READING_CONFIG_REQUEST = 'SET_READING_CONFIG_REQUEST';
export const SET_READING_CONFIG_SUCCESS = 'SET_READING_CONFIG_SUCCESS';
export const SET_READING_CONFIG_ASYNC_STORAGE_REQUEST =
  'SET_READING_CONFIG_ASYNC_STORAGE_REQUEST';

export const GET_PRE_LOAD_HOME_BLOCKS_REQUEST =
  'GET_PRE_LOAD_HOME_BLOCKS_REQUEST';
export const GET_PRE_LOAD_HOME_BLOCKS_SUCCESS =
  'GET_PRE_LOAD_HOME_BLOCKS_SUCCESS';

export const GET_HOME_BLOCKS_REQUEST = 'GET_HOME_BLOCKS_REQUEST';
export const GET_HOME_BLOCKS_SUCCESS = 'GET_HOME_BLOCKS_SUCCESS';
export const GET_HOME_BLOCKS_FAILURE = 'GET_HOME_BLOCKS_FAILURE';
export const GET_HOME_BLOCKS_RESET = 'GET_HOME_BLOCKS_RESET';

export const GET_ACTIVE_SUMMARY_DETAIL_REQUEST =
  'GET_ACTIVE_SUMMARY_DETAIL_REQUEST';
export const GET_ACTIVE_SUMMARY_DETAIL_SUCCESS =
  'GET_ACTIVE_SUMMARY_DETAIL_SUCCESS';
export const GET_ACTIVE_SUMMARY_DETAIL_FAILURE =
  'GET_ACTIVE_SUMMARY_DETAIL_FAILURE';
export const GET_ACTIVE_SUMMARY_DETAIL_RESET =
  'GET_ACTIVE_SUMMARY_DETAIL_RESET';

export const SET_STARTED_SUMMARY = 'SET_STARTED_SUMMARY';

export const GET_FAVORITE_LIST_REQUEST = 'GET_FAVORITE_LIST_REQUEST';
export const GET_FAVORITE_LIST_SUCCESS = 'GET_FAVORITE_LIST_SUCCESS';

export const GET_STARTED_BOOKS_REQUEST = 'GET_STARTED_BOOKS_REQUEST';
export const GET_STARTED_BOOKS_SUCCESS = 'GET_STARTED_BOOKS_SUCCESS';
export const GET_STARTED_BOOKS_FAILURE = 'GET_STARTED_BOOKS_FAILURE';
export const GET_STARTED_BOOKS_RESET = 'GET_STARTED_BOOKS_RESET';

export const GET_FINISHED_BOOKS_REQUEST = 'GET_FINISHED_BOOKS_REQUEST';
export const GET_FINISHED_BOOKS_SUCCESS = 'GET_FINISHED_BOOKS_SUCCESS';
export const GET_FINISHED_BOOKS_FAILURE = 'GET_FINISHED_BOOKS_FAILURE';
export const GET_FINISHED_BOOKS_RESET = 'GET_FINISHED_BOOKS_RESET';

export const FAVORITE_SUMMARY_REQUEST = 'FAVORITE_SUMMARY_REQUEST';
export const UNFAVORITE_SUMMARY_REQUEST = 'UNFAVORITE_SUMMARY_REQUEST';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_RESET = 'GET_CATEGORIES_RESET';

export const GET_CATEGORY_SUMMARIES_REQUEST = 'GET_CATEGORY_SUMMARIES_REQUEST';
export const GET_CATEGORY_SUMMARIES_SUCCESS = 'GET_CATEGORY_SUMMARIES_SUCCESS';
export const GET_CATEGORY_SUMMARIES_FAILURE = 'GET_CATEGORY_SUMMARIES_FAILURE';
export const GET_CATEGORY_SUMMARIES_RESET = 'GET_CATEGORY_SUMMARIES_RESET';

export const MAKE_SORT_CATEGORY_SUMMARIES_FROM_A_TO_Z =
  'MAKE_SORT_CATEGORY_BOOKS_FROM_A_TO_Z';
export const MAKE_SORT_CATEGORY_SUMMARIES_FROM_Z_TO_A =
  'MAKE_SORT_CATEGORY_BOOKS_FROM_Z_TO_A';

export const RESET_CATEGORY_SUMMARIES = 'RESET_CATEGORY_SUMMARIES';

export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const GET_SUMMARY_REQUEST = 'GET_SUMMARY_REQUEST';

export const SET_BOOK_CURRENT_PART = 'SET_BOOK_CURRENT_PART';

export const SET_ACTIVE_SUMMARY = 'SET_ACTIVE_SUMMARY';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const SET_ACTIVE_MAN_COMPOSITION = 'SET_ACTIVE_MAN_COMPOSITION';

export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';
export const SET_PLAYER_CURRENT_TRACK = 'SET_PLAYER_CURRENT_TRACK';
export const SET_PLAYER_RATE = 'SET_PLAYER_RATE';
export const SET_TRACK_FINISHED_FLAG = 'SET_TRACK_FINISHED_FLAG';

export const SET_FILTER_NOT_STARTED = 'SET_FILTER_NOT_STARTED';
export const SET_FILTER_STARTED = 'SET_FILTER_STARTED';
export const SET_FILTER_FINISHED = 'SET_FILTER_FINISHED';
export const SET_FILTER_SELECTED_CATEGORIES = 'SET_FILTER_SELECTED_CATEGORIES';

export const GET_DAILY_PICK_DETAIL_REQUEST = 'GET_DAILY_PICK_DETAIL_REQUEST';
export const GET_DAILY_PICK_DETAIL_SUCCESS = 'GET_DAILY_PICK_DETAIL_SUCCESS';
export const GET_DAILY_PICK_DETAIL_FAILURE = 'GET_DAILY_PICK_DETAIL_FAILURE';
export const GET_DAILY_PICK_DETAIL_RESET = 'GET_DAILY_PICK_DETAIL_RESET';

export const GET_MANS_COMPOSITIONS_LISTS_REQUEST =
  'GET_MANS_COMPOSITIONS_LISTS_REQUEST';
export const GET_MANS_COMPOSITIONS_LISTS_SUCCESS =
  'GET_MANS_COMPOSITIONS_LISTS_SUCCESS';
export const GET_MANS_COMPOSITIONS_LISTS_FAILURE =
  'GET_MANS_COMPOSITIONS_LISTS_FAILURE';
export const GET_MANS_COMPOSITIONS_LISTS_RESET =
  'GET_MANS_COMPOSITIONS_LISTS_RESET';

export const FINISH_SUMMARY_REQUEST = 'FINISH_SUMMARY_REQUEST';
export const FINISH_SUMMARY_SUCCESS = 'FINISH_SUMMARY_SUCCESS';
export const FINISH_SUMMARY_FAILURE = 'FINISH_SUMMARY_FAILURE';
export const FINISH_SUMMARY_RESET = 'FINISH_SUMMARY_RESET';

export const SET_IAP_PRODUCTS = 'SET_IAP_PRODUCTS';

export const SAVE_PREMIUM_SUBSCRIPTION_RECEIPT_REQUEST =
  'SAVE_PREMIUM_SUBSCRIPTION_RECEIPT_REQUEST';

export const DEACTIVATE_PREMIUM_REQUEST = 'DEACTIVATE_PREMIUM_REQUEST';
export const DEACTIVATE_PREMIUM_SUCCESS = 'DEACTIVATE_PREMIUM_SUCCESS';
export const DEACTIVATE_PREMIUM_FAILURE = 'DEACTIVATE_PREMIUM_FAILURE';
export const DEACTIVATE_PREMIUM_RESET = 'DEACTIVATE_PREMIUM_RESET';

export const SEND_DEVICE_INFO_REQUEST = 'SEND_DEVICE_INFO_REQUEST';
export const SAVE_ONESIGNAL_TO_ASYNC_STORAGE =
  'SAVE_ONESIGNAL_TO_ASYNC_STORAGE';

export const SEND_CONTACT_ME_MESSAGE_REQUEST =
  'SEND_CONTACT_ME_MESSAGE_REQUEST';
export const SEND_CONTACT_ME_MESSAGE_SUCCESS =
  'SEND_CONTACT_ME_MESSAGE_SUCCESS';
export const SEND_CONTACT_ME_MESSAGE_FAILURE =
  'SEND_CONTACT_ME_MESSAGE_FAILURE';
export const SEND_CONTACT_ME_MESSAGE_RESET = 'SEND_CONTACT_ME_MESSAGE_RESET';

export const GET_DAILY_NOTIFICATION_STATUS_REQUEST =
  'GET_DAILY_NOTIFICATION_STATUS_REQUEST';
export const GET_DAILY_NOTIFICATION_STATUS_SUCCESS =
  'GET_DAILY_NOTIFICATION_STATUS_SUCCESS';

export const SET_DAILY_NOTIFICATION_STATUS_REQUEST =
  'SET_DAILY_NOTIFICATION_STATUS_REQUEST';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const REMOVE_STARTED_SUMMARY = 'REMOVE_STARTED_SUMMARY';

export const SHOW_ALERT_DIALOG = 'SHOW_ALERT_DIALOG';

export const GA_LOG_EVENT_REQUEST = 'GA_LOG_EVENT_REQUEST';
export const GA_SIGN_IN_REQUEST = 'GA_SIGN_IN_REQUEST';
export const GA_TRACK_SCREEN_REQUEST = 'GA_TRACK_SCREEN_REQUEST';

export const RESENT_EMAIL_CONFIRM_REQUEST = 'RESENT_EMAIL_CONFIRM_REQUEST';

export const GET_SEARCH_BLOCKS_REQUEST = 'GET_SEARCH_BLOCKS_REQUEST';
export const GET_SEARCH_BLOCKS_SUCCESS = 'GET_SEARCH_BLOCKS_SUCCESS';
export const CONVERT_INSTAGRAM_SHARE_URL_TO_BASE64_REQUEST =
  'CONVERT_INSTAGRAM_SHARE_URL_TO_BASE64_REQUEST';
export const CONVERT_INSTAGRAM_SHARE_URL_TO_BASE64_SUCCESS =
  'CONVERT_INSTAGRAM_SHARE_URL_TO_BASE64_SUCCESS';
